c_compiler:                  # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]

cxx_compiler:                  # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
