{% set name = "rapidfuzz" %}
{% set version = "0.7.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 543eecc93a5f7c37f04f5d528775b2799f5e7f771b2a06351e41ab5b69280d44

build:
  number: 0
  skip: true  # [py2k]
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - rapidfuzz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxbachmann/rapidfuzz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: rapid fuzzy string matching
  dev_url: https://github.com/maxbachmann/rapidfuzz


extra:
  recipe-maintainers:
    - maxbachmann
