{% set name = "rapidfuzz" %}
{% set version = "3.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rapidfuzz-{{ version }}.tar.gz
  sha256: b398ea66e8ed50451bce5997c430197d5e4b06ac4aa74602717f792d8d8d06e2
  patches:
    - cmake_verfix.patch

build:
  number: 0
  skip: True  # [py<38]
  missing_dso_whitelist:  # [s390x]
    - '$RPATH/ld64.so.1'  # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make         # [not win]
    - ninja-base   # [win]
    - patch        # [not win]
    - m2-patch     # [win]
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
    - scikit-build
    - cython >=3.0.9,<3.1.0
  run:
    - python
    - numpy

test:
  imports:
    - rapidfuzz
    - rapidfuzz.distance
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/rapidfuzz/RapidFuzz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: rapid fuzzy string matching
  description: Rapid fuzzy string matching in Python using various string metrics
  dev_url: https://github.com/rapidfuzz/RapidFuzz
  doc_url: https://rapidfuzz.github.io/RapidFuzz

extra:
  recipe-maintainers:
    - maxbachmann
