{% set name = "rapidfuzz" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd7a4fe33ba49db3417f0f57a8af02462554f1296dedcf35b026cd3525efef74

build:
  number: 0
  skip: True  # [py<37]
  script:
    - {{ PYTHON }} -m pip install . -vvv
  missing_dso_whitelist:  # [s390x]
    - '$RPATH/ld64.so.1'  # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy   1.19   # [py<310]
    - numpy   1.21   # [py==310]
    - numpy   1.23   # [py>=311]
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - rapidfuzz
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/maxbachmann/RapidFuzz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: rapid fuzzy string matching
  dev_url: https://github.com/maxbachmann/RapidFuzz
  doc_url: https://maxbachmann.github.io/RapidFuzz/

extra:
  recipe-maintainers:
    - maxbachmann
