{% set name = "rapidfuzz" %}
{% set version = "3.14.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rapidfuzz-{{ version }}.tar.gz
  sha256: e13a8160d017b499ec7a2fa9d0ce1ae2e7377080815785819f966fb235d4eb60

build:
  number: 0
  skip: true  # [py<311]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make  # [not win]
  host:
    - python
    - pip
    - cython >=3.1.6,<3.3.0
    - scikit-build-core >=0.11
  run:
    - python

test:
  source_files: tests
  imports:
    - rapidfuzz
    - rapidfuzz._common_py
    - rapidfuzz._feature_detector
    - rapidfuzz._utils
    - rapidfuzz.distance
    - rapidfuzz.distance._initialize_cpp
    - rapidfuzz.distance._initialize_py
    - rapidfuzz.distance.DamerauLevenshtein_py
    - rapidfuzz.distance.Hamming_py
    - rapidfuzz.distance.Indel_py
    - rapidfuzz.distance.Jaro_py
    - rapidfuzz.distance.JaroWinkler_py
    - rapidfuzz.distance.LCSseq_py
    - rapidfuzz.distance.Levenshtein_py
    - rapidfuzz.distance.OSA_py
    - rapidfuzz.distance.Postfix_py
    - rapidfuzz.distance.Prefix_py
    - rapidfuzz.fuzz
    - rapidfuzz.process_cpp_impl
    - rapidfuzz.utils
  requires:
    - pip
    - pytest
    - hypothesis
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/maxbachmann/RapidFuzz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: rapid fuzzy string matching
  description: Rapid fuzzy string matching in Python using various string metrics
  dev_url: https://github.com/maxbachmann/RapidFuzz
  doc_url: https://maxbachmann.github.io/RapidFuzz

extra:
  recipe-maintainers:
    - maxbachmann
