{% set name = "rapidfuzz" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e479212f8f6eaf6bbc9ac5418320a49ae09ad942d3bd437b9db7e0a37c56f819

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - rapidfuzz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxbachmann/rapidfuzz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: rapid fuzzy string matching
  dev_url: https://github.com/maxbachmann/rapidfuzz
  doc_url: https://maxbachmann.github.io/rapidfuzz/

extra:
  recipe-maintainers:
    - maxbachmann
